---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis
  labels:
    type: local
spec:
  storageClassName: manual
  claimRef:
    name: redis-claim0
    namespace: mastodon
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/persistent-volumes/mastodon-redis
