apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: db-claim0
  name: db-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: manual
status: {}
