---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: manual
status: {}
