---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mastodon

resources:
  - configmap.yaml
  - db-claim0-persistentvolumeclaim.yaml
  - db-deployment.yaml
  - db-service.yaml
  - es-claim0-persistentvolumeclaim.yaml
  - es-deployment.yaml
  - es-service.yaml
  - redis-claim0-persistentvolumeclaim.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - sidekiq-deployment.yaml
  - streaming-deployment.yaml
  - streaming-service.yaml
  - web-claim0-persistentvolumeclaim.yaml
  - web-deployment.yaml
  - web-service.yaml
  - traefik.yaml

secretGenerator:
  - name: mastodon
    envs:
      - secret.env

images:
  - name: tootsuite/mastodon
    newTag: v3.4.6
