---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sidekiq
  name: sidekiq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidekiq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sidekiq
    spec:
      containers:
        - args:
            - bundle
            - exec
            - sidekiq
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mastodon
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mastodon
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mastodon
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mastodon
                  key: DB_USERNAME
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mastodon
                  key: DB_PASSWORD
            - name: DEFAULT_LOCALE
              valueFrom:
                configMapKeyRef:
                  name: mastodon
                  key: DEFAULT_LOCALE
            - name: ES_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: mastodon
                  key: ES_ENABLED
            - name: ES_HOST
              valueFrom:
                configMapKeyRef:
                  name: mastodon
                  key: ES_HOST
            - name: ES_PORT
              valueFrom:
                configMapKeyRef:
                  name: mastodon
                  key: ES_PORT
            - name: LOCAL_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: mastodon
                  key: LOCAL_DOMAIN
            - name: OTP_SECRET
              valueFrom:
                secretKeyRef:
                  name: mastodon
                  key: OTP_SECRET
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: mastodon
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: mastodon
                  key: REDIS_PORT
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: mastodon
                  key: SECRET_KEY_BASE
            - name: SINGLE_USER_MODE
              valueFrom:
                configMapKeyRef:
                  name: mastodon
                  key: SINGLE_USER_MODE
            - name: SMTP_DELIVERY_METHOD
              valueFrom:
                configMapKeyRef:
                  name: mastodon
                  key: SMTP_DELIVERY_METHOD
            - name: SMTP_FROM_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: mastodon
                  key: SMTP_FROM_ADDRESS
            - name: SMTP_LOGIN
              valueFrom:
                secretKeyRef:
                  name: mastodon
                  key: SMTP_USERNAME
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mastodon
                  key: SMTP_PASSWORD
            - name: SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: mastodon
                  key: SMTP_PORT
            - name: SMTP_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mastodon
                  key: SMTP_SERVER
            - name: SMTP_TLS
              valueFrom:
                configMapKeyRef:
                  name: mastodon
                  key: SMTP_TLS
            - name: STREAMING_CLUSTER_NUM
              valueFrom:
                configMapKeyRef:
                  name: mastodon
                  key: STREAMING_CLUSTER_NUM
            - name: VAPID_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: mastodon
                  key: VAPID_PRIVATE_KEY
            - name: VAPID_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: mastodon
                  key: VAPID_PUBLIC_KEY
          image: tootsuite/mastodon:v3.4.6
          name: sidekiq
          resources: {}
          volumeMounts:
            - mountPath: /mastodon/public/system
              name: web-claim0
      restartPolicy: Always
      volumes:
        - name: web-claim0
          persistentVolumeClaim:
            claimName: web-claim0
status: {}
